# https://www.serverless.com/blog/serverless-python-packaging

service: numpy-test

provider:
  name: aws
  runtime: python3.7

functions:
  numpy:
    handler: handler.main
    events:
      - http:
          path: hello
          method: get
          cors:
            headers: "*"
    layers:
      - arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python37-SciPy1x:37

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
